### ISSUE TITLE
Workflows v1 Feedback2

### ISSUE THREAD

**Issue by eins78** [Madek/madek#248]
- [x] https://github.com/Madek/madek/issues/246

- [x] https://github.com/Madek/madek/issues/245

- [x] The order of the Input Fields in the Check or Fill Data steps of a workflow should be the same order as the keys are defined in the 'common metadata' list. E.g.: If I add a new field, it will be the last in the list and should also be the last input field.

- [ ] show existing values when workflow will override with a fixed value. 
  - [x] in every edit form (normal, batch, part of workflow), show a message (can not edit here, see workflow) 
  - [ ] new:  _if there is an existing value_, show a warning and the old value 
    ```
    <detail><summary>Warning: the current value will be overridden (click to show)</summary><div>{old value}</div></detail>
    ```

- [x] Falsches Feld in Default-Liste „weitere Beteiligte Personen“
  - Es sollte Feld [media_object: creative_participants_roles) sein
  - checken das Rollen funktionieren!

- [x] Checkboxen lassen sich nicht ausfüllen im „Ausfüllen“-Modus“ (Firefox, Safari…)
Feld „Kunstgattung / Disziplin“ (media_content: type) lässt sich nicht ausfüllen, auch nicht Rechtsschutz im Ausfüllen-Modus. Im Meta-Edit-Modus können die Felder aber problemlos mit fixen Werten versehen werden (ebenfalls Checkbox)

- [x] Voreinstellungen Set/ME
in Übersicht Workflow Ergänzung bei Metafelder ob es betrifft Set und/oder ME

- [x] Benutzerrechte: PDF blättern/Original exportieren erwähnen bei kombinierter Option

- [x] ME in mehreren Sets!
ME, der in Unterset verschoben wird, kann in mehreren Sets aufauchen. Unterschiedliche Eintraäge bei Autoren werden zusammengefasst (super !). Beim Titel ergibt das Speichern aber einen Fehler. Testset: https://madek-spiel.kiste.li/my/workflows/ef02af1f-c0c0-4037-a7f2-eea2b075f3b5

- [x] Reihenfolge der Felder in Übersicht und auf Prüf-Seite entspricht nicht der Mapping-Vorgabe:
  - siehe Reihenfolge unter der Tabelle, die Tabelle selbst ist anders sortiert!

- [x] automatische Beschreibung enfernen/verschieben
Im Feld Beschreibung steht eine automatische Beschreibung:
   - Nach Änderung von Name von Workflow oder Oberset wird der Titel im Beschreibungstext nicht angepasst.
   - automatischer Beschreibungstext aus Feld Beschreibung entfernen und in neues Feld „Forschungsprojekt Zugehörigkeit“

- [x] Meine Workflows Reihenfolge
  - nach "created_at DESC" sortieren
  - gruppieren nach status

- [x] Übersicht: Meta-Edit-Stift geht nicht weg in Edit-Mode.

---

neu gefunden:

- [x] es können metakeys hinzugefügt werden, die der Nutzer selbst nicht bearbeiten kann! 
    * nicht per autocomplete hinzufügbar machen?
    * extra auszeichnen in der Tabelle?

---

extra

- während sub-sektionen bearbeitet werden, sind die haupt-aktionsbuttons ausgeblendet (damit nicht aus versehen auf den falschen Speicher button geklickt wird)

---

### scratchpad texte

> Die für diesen Prozess relevanten Metadaten-Felder und ihre Einstellungen und Werte. "Fixe Werte" können nur an dieser Stelle vergeben werden und werden nach Abschluss der Prozesses auf alle Inhalte angewendet. Felder mit "Individueller Vergabe" stehen im Schritt "Daten eingeben" zur massenweise Eingabe zur Verfügung.

> * Verantwortliche Person(en):
> * Schreib- und Leserechte:
> * Nur Leserechte:
> * Öffentlicher Zugriff (Internet)
>
> *Leserechte umfassen "Betrachten" der Metadaten und Vorschau, sowie "Original exportieren & in PDF blättern".*

> *Reading permissions and public access include “View” for metadata und previews, as well as “Download original & browse PDF”.*

**Comment by eins78** [comment]
neu gefunden:

- [ ] es können metakeys hinzugefügt werden, die der Nutzer selbst nicht bearbeiten kann! 
    * nicht per autocomplete hinzufügbar machen?
    * extra auszeichnen in der Tabelle?

**Comment by eins78** [comment]
@phoettli habe es mal so in die Tabelle getan. Hast du eine bessere Idee für den Titel als "Scope"?  Ich dachte erst 2 Spalten zu machen wie bei Pflichtfeld, also Eintrag|Set und dann jeweils ein **X** oder ✔️, aber so viele Icons sind nicht gerade übersichtlich.

<img width="587" alt="Screen Shot 2020-06-09 at 08 58 06" src="https://user-images.githubusercontent.com/134942/84116239-bb40ea80-aa2f-11ea-9fe9-84170e4e9c74.png">

**Comment by phoettli** [comment]
ich finds gut so mit "Einträte & Sets". Bezeichnung: "Geltungsbereich" oder "Auftreten" passt für mich beides.

**Comment by eins78** [comment]
Bzgl der MetaKeys im gemeinsamen Datensatz werden jetzt weniger Fehler ignoriert und dafür als Probleme angezeigt.

---

<img width="649" alt="Screen Shot 2020-06-16 at 15 04 25" src="https://user-images.githubusercontent.com/134942/84778176-e5237f80-afe2-11ea-80e0-ae35c49aa855.png">

---

<img width="763" alt="Screen Shot 2020-06-16 at 15 04 36" src="https://user-images.githubusercontent.com/134942/84778186-e94f9d00-afe2-11ea-9cba-cb577b7a8ccf.png">
