### ISSUE TITLE
Webapp enhancement 2nd part 2020 (Michal)

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#259]
Paket 1

- [x] 1. Optionale Auswahl für Core-Feld „Urheberrechtshinweis“ #258
(optional select in core field „Copyright notice“ #258)

- [x] 2. Sortierung übernehmen für API #205
(Webapp sort methods and orders in sets readable via API #205)

- [x] 3. Manuelle Sortierung von MEs in Set #204
(additional manual sorting in sets #204)

Paket 2

- [x] 4. Gruppen für Verantwortung Set & ME #206
(responsible user can also be a Group (ME & Set) #206)

- [x] 5. Zugang gleiches Set unter ähnliche Inhalte #268
(show sibling entries from same set(s) on top of “similar items” #268)

- [x] 6. Medieneintrag ersetzen #269 (oder ähnliches Issue)
(replace ME with same metadata and permissions (or similar issue) #269)
