### ISSUE TITLE
Filter-Update 2020 (Sammel-Issue)

### ISSUE THREAD

**Issue by phoettli** [Madek/madek#283]
Filter-Section ergänzen (Sammel-Issue)

- [x] in Filter nach API-Berechtigung suchen #95 
nur intern sichtbar!

- [x] Delegation in Filter sichtbar machen #281 

- [x] Verantwortung und Benutzer nur intern sichtbar #282

**Comment by phoettli** [comment]
✅
