### ISSUE TITLE
Meta-Key Listentypen erweitern

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#651]
Der Listentyp der Meta-Keys (`MetaDatum::Keywords`) gibt es nur als MultiSelect:

- als erweiterbare Liste wird er dargestellt als DropDown mit Such- bzw. Eingabefeld
`is_extensible_list=true`
<img width="696" alt="image" src="https://github.com/user-attachments/assets/ba6aa2a8-7bed-4f92-94fb-34e404d4b376">

- als nicht erweiterbare Liste wird er dargestellt bis 16 Keywords als Checkboxen
`is_extensible_list=false`
<img width="678" alt="image" src="https://github.com/user-attachments/assets/60f7fadd-a22c-4295-a7dc-26c2e0e511c7">

- ab 17 Keywords wird automatisch eine Liste dargestellt – ohne dass die Darstellung explizit gewählt werden könnte
<img width="700" alt="image" src="https://github.com/user-attachments/assets/ca56e450-79c2-4fd5-bdb0-fffa7b2e3599">

----

es fehlt:

- [ ] Darstellung der Mehrfachauswahl als Parameter wählen (DropDown oder Checkbox)
z.B. `List type: auto, List, Mark`

- [ ] SingleSelect
z.B. `Option: SingleSelect, MultiSelect`
...bis 16 Keywords als Radioboxen
<img width="825" alt="image" src="https://github.com/user-attachments/assets/5d448df0-e8c7-42e1-bda2-cd6ea3cc1186">

... ab 17 Keywords DropDown
(Darstellungsbeispiel "Rechteinhaber/in"):
<img width="713" alt="image" src="https://github.com/user-attachments/assets/c6fcfa22-e8a8-4b90-bbf0-3fc96f2255ba">

zu beachten:
  - [ ] Möglichkeit zur Entfernung der Markierung bei Radio
<img width="84" alt="image" src="https://github.com/user-attachments/assets/84a3ec24-56b8-47bb-8dff-ade6325e6a49">

  - [ ] Wechsel von SingleSelect zu MultiSelect ohne Probleme möglich, aber von Multi zu Single nur, wenn nur noch ein Keyword besteht

  - [ ] SingleSelect-Liste kann logischerweise nicht erweitert werden `Extensible?=false`

- [ ] Reihenfolge der Keywords möglich, wenn nicht alphabetisch sortiert (seperates Ticket ?)

**Comment by urs-van-binsbergen** [comment]
Offene Punkte: 
- Webapp Specs
- Dropdown für Single Select optimieren. Aktueller Zustand: <img width="466" alt="image" src="https://github.com/user-attachments/assets/7d4f5f10-c732-4762-8dfb-eefbe71bcf08">
- Harte DB-Constraint, die verhindert, dass entgegen der Konfiguration "Single selection"  mehrere Keywords zugeordnet werden
- Auswirkungen auf API v1 (vermutlich keine)
- Auswirkungen auf API v2
  - 2 neue Felder auf Entität `meta_keys` abbilden/validieren
  - Applikatorische Validierung der Keyword-Zuordnungen
    - Achtung: aktuelles API-Design erlaubt keine transaktionale Speicherung der Keyword-Zuordnungen, nur sequentielles POST und DELETE

**Comment by urs-van-binsbergen** [comment]
d179e7161c718695fe5a2b6af205600b7e2bcfad
