### ISSUE TITLE
File-Upload erneuern

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#670]
Der File-Upload- und -Verarbeitungsprozess stösst an Grenzen insb. bei grossen Files.

In Media-Service sind diese Teilprozesse neu und asynchron definiert.

Upload- und Verarbeitungsprozess neu implementieren.

- [ ] Prüfsumme erstellen
- [ ] Upload in Teilstücken (Chunks)
- [ ] Medieneintrag erstellen
- [ ] asynchrone Schritte
  - [ ] File Prüfung
  - [ ] Metadaten auslesen
  - [ ] File verschieben
- [ ] für Preview-Erstellung übergeben
- [ ] ...

In Frontend einbauen

- [ ] Upload inkl. Upload-Status
- [ ] Rückmeldungen
  - [ ] Erstellter Medieneintrag
  - [ ] Verarbeitung
  - [ ] Preview-Erstellung
  - [ ] abgeschlossene Previews
  - [ ] Notifikation für abgeschlossene Previews
