### ISSUE TITLE
DB: `external_uri` should take list of values

### ISSUE THREAD

**Issue by eins78** [Madek/madek#74]
2 times, columns in both tables `keywords` and `people`

- [x] db: migrate schema + data to array
- [x] admin: edit fields support multiple values
- [x] admin: index/show support array of links
- [x] webapp: show pages support array of links

**Comment by nadjaweisskopf** [comment]
@eins78 Refinement with Philipp, Matus, Thomas and Tashi: 
first question: one screenshot is a person, one is a tag
solutions: 
1. As good as possible - check URL, split on white space and commas
2. solution from Max
3. Shouldn't we rather introduce meta keys on persons too --> RDF-scheme - think about this solution too

Decide, if only for this field or for all necessary fields.

**Comment by nadjaweisskopf** [comment]
could be a ticket for Michal - but not very important

**Comment by eins78** [comment]
finished DB migration and API backwards-compatibilty
https://github.com/Madek/madek/commit/6a2e98269560bb304260ed4625c48b627c41b1de

**Comment by eins78** [comment]
finished 
- editing in admin ui (people and keywords)
- display list of URIs (people and keywords)
- for people, decorate some known links ("Normdaten", see below)
- test for everything

![Screen Shot 2019-04-12 at 17 19 13](https://user-images.githubusercontent.com/134942/56048258-63cdbe80-5d47-11e9-9e1a-48a882d3e334.png)
